/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-postgres";
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  numeric,
  boolean,
  jsonb,
  pgEnum,
} from "@payloadcms/db-postgres/drizzle/pg-core";
import { sql, relations } from "@payloadcms/db-postgres/drizzle";
export const enum__locales = pgEnum("enum__locales", ["en", "it"]);
export const enum_users_role = pgEnum("enum_users_role", ["admin", "staff"]);
export const enum_tours_status = pgEnum("enum_tours_status", [
  "draft",
  "published",
]);
export const enum__tours_v_version_status = pgEnum(
  "enum__tours_v_version_status",
  ["draft", "published"],
);
export const enum__tours_v_published_locale = pgEnum(
  "enum__tours_v_published_locale",
  ["en", "it"],
);
export const enum_bookings_status = pgEnum("enum_bookings_status", [
  "pending",
  "reserved",
  "confirmed",
  "cancelled",
  "refunded",
  "failed",
]);
export const enum_blog_posts_status = pgEnum("enum_blog_posts_status", [
  "draft",
  "published",
]);
export const enum__blog_posts_v_version_status = pgEnum(
  "enum__blog_posts_v_version_status",
  ["draft", "published"],
);
export const enum__blog_posts_v_published_locale = pgEnum(
  "enum__blog_posts_v_published_locale",
  ["en", "it"],
);
export const enum_pages_status = pgEnum("enum_pages_status", [
  "draft",
  "published",
]);
export const enum__pages_v_version_status = pgEnum(
  "enum__pages_v_version_status",
  ["draft", "published"],
);
export const enum__pages_v_published_locale = pgEnum(
  "enum__pages_v_published_locale",
  ["en", "it"],
);

export const users_sessions = pgTable(
  "users_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index("users_sessions_order_idx").on(columns._order),
    index("users_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const users = pgTable(
  "users",
  {
    id: serial("id").primaryKey(),
    firstName: varchar("first_name"),
    lastName: varchar("last_name"),
    role: enum_users_role("role").notNull().default("staff"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    email: varchar("email").notNull(),
    resetPasswordToken: varchar("reset_password_token"),
    resetPasswordExpiration: timestamp("reset_password_expiration", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar("salt"),
    hash: varchar("hash"),
    loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
    lockUntil: timestamp("lock_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("users_updated_at_idx").on(columns.updatedAt),
    index("users_created_at_idx").on(columns.createdAt),
    uniqueIndex("users_email_idx").on(columns.email),
  ],
);

export const media = pgTable(
  "media",
  {
    id: serial("id").primaryKey(),
    alt: varchar("alt").notNull(),
    caption: varchar("caption"),
    prefix: varchar("prefix").default("media"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
    sizes_thumbnail_url: varchar("sizes_thumbnail_url"),
    sizes_thumbnail_width: numeric("sizes_thumbnail_width", { mode: "number" }),
    sizes_thumbnail_height: numeric("sizes_thumbnail_height", {
      mode: "number",
    }),
    sizes_thumbnail_mimeType: varchar("sizes_thumbnail_mime_type"),
    sizes_thumbnail_filesize: numeric("sizes_thumbnail_filesize", {
      mode: "number",
    }),
    sizes_thumbnail_filename: varchar("sizes_thumbnail_filename"),
    sizes_card_url: varchar("sizes_card_url"),
    sizes_card_width: numeric("sizes_card_width", { mode: "number" }),
    sizes_card_height: numeric("sizes_card_height", { mode: "number" }),
    sizes_card_mimeType: varchar("sizes_card_mime_type"),
    sizes_card_filesize: numeric("sizes_card_filesize", { mode: "number" }),
    sizes_card_filename: varchar("sizes_card_filename"),
    sizes_hero_url: varchar("sizes_hero_url"),
    sizes_hero_width: numeric("sizes_hero_width", { mode: "number" }),
    sizes_hero_height: numeric("sizes_hero_height", { mode: "number" }),
    sizes_hero_mimeType: varchar("sizes_hero_mime_type"),
    sizes_hero_filesize: numeric("sizes_hero_filesize", { mode: "number" }),
    sizes_hero_filename: varchar("sizes_hero_filename"),
  },
  (columns) => [
    index("media_updated_at_idx").on(columns.updatedAt),
    index("media_created_at_idx").on(columns.createdAt),
    uniqueIndex("media_filename_idx").on(columns.filename),
    index("media_sizes_thumbnail_sizes_thumbnail_filename_idx").on(
      columns.sizes_thumbnail_filename,
    ),
    index("media_sizes_card_sizes_card_filename_idx").on(
      columns.sizes_card_filename,
    ),
    index("media_sizes_hero_sizes_hero_filename_idx").on(
      columns.sizes_hero_filename,
    ),
  ],
);

export const countries = pgTable(
  "countries",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    code: varchar("code").notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("countries_code_idx").on(columns.code),
    index("countries_updated_at_idx").on(columns.updatedAt),
    index("countries_created_at_idx").on(columns.createdAt),
  ],
);

export const tour_categories = pgTable(
  "tour_categories",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    slug: varchar("slug").notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("tour_categories_slug_idx").on(columns.slug),
    index("tour_categories_updated_at_idx").on(columns.updatedAt),
    index("tour_categories_created_at_idx").on(columns.createdAt),
  ],
);

export const tours_gallery = pgTable(
  "tours_gallery",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    image: integer("image_id").references(() => media.id, {
      onDelete: "set null",
    }),
  },
  (columns) => [
    index("tours_gallery_order_idx").on(columns._order),
    index("tours_gallery_parent_id_idx").on(columns._parentID),
    index("tours_gallery_image_idx").on(columns.image),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [tours.id],
      name: "tours_gallery_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const tours_highlights = pgTable(
  "tours_highlights",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    text: varchar("text"),
  },
  (columns) => [
    index("tours_highlights_order_idx").on(columns._order),
    index("tours_highlights_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [tours.id],
      name: "tours_highlights_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const tours_included = pgTable(
  "tours_included",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    item: varchar("item"),
  },
  (columns) => [
    index("tours_included_order_idx").on(columns._order),
    index("tours_included_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [tours.id],
      name: "tours_included_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const tours_excluded = pgTable(
  "tours_excluded",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    item: varchar("item"),
  },
  (columns) => [
    index("tours_excluded_order_idx").on(columns._order),
    index("tours_excluded_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [tours.id],
      name: "tours_excluded_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const tours_itinerary = pgTable(
  "tours_itinerary",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    time: varchar("time"),
    title: varchar("title"),
    description: varchar("description"),
  },
  (columns) => [
    index("tours_itinerary_order_idx").on(columns._order),
    index("tours_itinerary_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [tours.id],
      name: "tours_itinerary_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const tours_reviews = pgTable(
  "tours_reviews",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    author: varchar("author"),
    rating: numeric("rating", { mode: "number" }),
    comment: varchar("comment"),
    date: timestamp("date", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("tours_reviews_order_idx").on(columns._order),
    index("tours_reviews_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [tours.id],
      name: "tours_reviews_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const tours = pgTable(
  "tours",
  {
    id: serial("id").primaryKey(),
    title: varchar("title"),
    slug: varchar("slug"),
    status: enum_tours_status("status").default("draft"),
    featured: boolean("featured").default(false),
    bokunActivityId: numeric("bokun_activity_id", { mode: "number" }),
    shortDescription: varchar("short_description"),
    description: jsonb("description"),
    coverImage: integer("cover_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    rating: numeric("rating", { mode: "number" }).default(4.5),
    reviewCount: numeric("review_count", { mode: "number" }).default(0),
    duration: varchar("duration"),
    country: integer("country_id").references(() => countries.id, {
      onDelete: "set null",
    }),
    location: varchar("location"),
    seo_metaTitle: varchar("seo_meta_title"),
    seo_metaDescription: varchar("seo_meta_description"),
    seo_ogImage: integer("seo_og_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    _status: enum_tours_status("_status").default("draft"),
  },
  (columns) => [
    uniqueIndex("tours_slug_idx").on(columns.slug),
    index("tours_cover_image_idx").on(columns.coverImage),
    index("tours_country_idx").on(columns.country),
    index("tours_seo_seo_og_image_idx").on(columns.seo_ogImage),
    index("tours_updated_at_idx").on(columns.updatedAt),
    index("tours_created_at_idx").on(columns.createdAt),
    index("tours__status_idx").on(columns._status),
  ],
);

export const tours_rels = pgTable(
  "tours_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    "tour-categoriesID": integer("tour_categories_id"),
  },
  (columns) => [
    index("tours_rels_order_idx").on(columns.order),
    index("tours_rels_parent_idx").on(columns.parent),
    index("tours_rels_path_idx").on(columns.path),
    index("tours_rels_tour_categories_id_idx").on(columns["tour-categoriesID"]),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [tours.id],
      name: "tours_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["tour-categoriesID"]],
      foreignColumns: [tour_categories.id],
      name: "tours_rels_tour_categories_fk",
    }).onDelete("cascade"),
  ],
);

export const _tours_v_version_gallery = pgTable(
  "_tours_v_version_gallery",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: serial("id").primaryKey(),
    image: integer("image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    _uuid: varchar("_uuid"),
  },
  (columns) => [
    index("_tours_v_version_gallery_order_idx").on(columns._order),
    index("_tours_v_version_gallery_parent_id_idx").on(columns._parentID),
    index("_tours_v_version_gallery_image_idx").on(columns.image),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_tours_v.id],
      name: "_tours_v_version_gallery_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _tours_v_version_highlights = pgTable(
  "_tours_v_version_highlights",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: serial("id").primaryKey(),
    text: varchar("text"),
    _uuid: varchar("_uuid"),
  },
  (columns) => [
    index("_tours_v_version_highlights_order_idx").on(columns._order),
    index("_tours_v_version_highlights_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_tours_v.id],
      name: "_tours_v_version_highlights_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _tours_v_version_included = pgTable(
  "_tours_v_version_included",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: serial("id").primaryKey(),
    item: varchar("item"),
    _uuid: varchar("_uuid"),
  },
  (columns) => [
    index("_tours_v_version_included_order_idx").on(columns._order),
    index("_tours_v_version_included_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_tours_v.id],
      name: "_tours_v_version_included_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _tours_v_version_excluded = pgTable(
  "_tours_v_version_excluded",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: serial("id").primaryKey(),
    item: varchar("item"),
    _uuid: varchar("_uuid"),
  },
  (columns) => [
    index("_tours_v_version_excluded_order_idx").on(columns._order),
    index("_tours_v_version_excluded_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_tours_v.id],
      name: "_tours_v_version_excluded_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _tours_v_version_itinerary = pgTable(
  "_tours_v_version_itinerary",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: serial("id").primaryKey(),
    time: varchar("time"),
    title: varchar("title"),
    description: varchar("description"),
    _uuid: varchar("_uuid"),
  },
  (columns) => [
    index("_tours_v_version_itinerary_order_idx").on(columns._order),
    index("_tours_v_version_itinerary_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_tours_v.id],
      name: "_tours_v_version_itinerary_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _tours_v_version_reviews = pgTable(
  "_tours_v_version_reviews",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: serial("id").primaryKey(),
    author: varchar("author"),
    rating: numeric("rating", { mode: "number" }),
    comment: varchar("comment"),
    date: timestamp("date", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    _uuid: varchar("_uuid"),
  },
  (columns) => [
    index("_tours_v_version_reviews_order_idx").on(columns._order),
    index("_tours_v_version_reviews_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_tours_v.id],
      name: "_tours_v_version_reviews_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _tours_v = pgTable(
  "_tours_v",
  {
    id: serial("id").primaryKey(),
    parent: integer("parent_id").references(() => tours.id, {
      onDelete: "set null",
    }),
    version_title: varchar("version_title"),
    version_slug: varchar("version_slug"),
    version_status:
      enum__tours_v_version_status("version_status").default("draft"),
    version_featured: boolean("version_featured").default(false),
    version_bokunActivityId: numeric("version_bokun_activity_id", {
      mode: "number",
    }),
    version_shortDescription: varchar("version_short_description"),
    version_description: jsonb("version_description"),
    version_coverImage: integer("version_cover_image_id").references(
      () => media.id,
      {
        onDelete: "set null",
      },
    ),
    version_rating: numeric("version_rating", { mode: "number" }).default(4.5),
    version_reviewCount: numeric("version_review_count", {
      mode: "number",
    }).default(0),
    version_duration: varchar("version_duration"),
    version_country: integer("version_country_id").references(
      () => countries.id,
      {
        onDelete: "set null",
      },
    ),
    version_location: varchar("version_location"),
    version_seo_metaTitle: varchar("version_seo_meta_title"),
    version_seo_metaDescription: varchar("version_seo_meta_description"),
    version_seo_ogImage: integer("version_seo_og_image_id").references(
      () => media.id,
      {
        onDelete: "set null",
      },
    ),
    version_updatedAt: timestamp("version_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp("version_created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version__status:
      enum__tours_v_version_status("version__status").default("draft"),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    snapshot: boolean("snapshot"),
    publishedLocale: enum__tours_v_published_locale("published_locale"),
    latest: boolean("latest"),
  },
  (columns) => [
    index("_tours_v_parent_idx").on(columns.parent),
    index("_tours_v_version_version_slug_idx").on(columns.version_slug),
    index("_tours_v_version_version_cover_image_idx").on(
      columns.version_coverImage,
    ),
    index("_tours_v_version_version_country_idx").on(columns.version_country),
    index("_tours_v_version_seo_version_seo_og_image_idx").on(
      columns.version_seo_ogImage,
    ),
    index("_tours_v_version_version_updated_at_idx").on(
      columns.version_updatedAt,
    ),
    index("_tours_v_version_version_created_at_idx").on(
      columns.version_createdAt,
    ),
    index("_tours_v_version_version__status_idx").on(columns.version__status),
    index("_tours_v_created_at_idx").on(columns.createdAt),
    index("_tours_v_updated_at_idx").on(columns.updatedAt),
    index("_tours_v_snapshot_idx").on(columns.snapshot),
    index("_tours_v_published_locale_idx").on(columns.publishedLocale),
    index("_tours_v_latest_idx").on(columns.latest),
  ],
);

export const _tours_v_rels = pgTable(
  "_tours_v_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    "tour-categoriesID": integer("tour_categories_id"),
  },
  (columns) => [
    index("_tours_v_rels_order_idx").on(columns.order),
    index("_tours_v_rels_parent_idx").on(columns.parent),
    index("_tours_v_rels_path_idx").on(columns.path),
    index("_tours_v_rels_tour_categories_id_idx").on(
      columns["tour-categoriesID"],
    ),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [_tours_v.id],
      name: "_tours_v_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["tour-categoriesID"]],
      foreignColumns: [tour_categories.id],
      name: "_tours_v_rels_tour_categories_fk",
    }).onDelete("cascade"),
  ],
);

export const bookings = pgTable(
  "bookings",
  {
    id: serial("id").primaryKey(),
    bookingReference: varchar("booking_reference").notNull(),
    tour: integer("tour_id")
      .notNull()
      .references(() => tours.id, {
        onDelete: "set null",
      }),
    status: enum_bookings_status("status").notNull().default("pending"),
    customer_firstName: varchar("customer_first_name").notNull(),
    customer_lastName: varchar("customer_last_name").notNull(),
    customer_email: varchar("customer_email").notNull(),
    customer_phone: varchar("customer_phone"),
    customerEmail: varchar("customer_email").notNull(),
    tourDate: timestamp("tour_date", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
    tourTime: varchar("tour_time").notNull(),
    startTimeId: numeric("start_time_id", { mode: "number" }),
    rateId: numeric("rate_id", { mode: "number" }).notNull(),
    availabilityId: varchar("availability_id").notNull(),
    adults: numeric("adults", { mode: "number" }).notNull(),
    children: numeric("children", { mode: "number" }).notNull().default(0),
    pricing_adultPrice: numeric("pricing_adult_price", {
      mode: "number",
    }).notNull(),
    pricing_childPrice: numeric("pricing_child_price", {
      mode: "number",
    }).notNull(),
    pricing_totalAmount: numeric("pricing_total_amount", {
      mode: "number",
    }).notNull(),
    pricing_currency: varchar("pricing_currency").notNull().default("EUR"),
    bokunConfirmationCode: varchar("bokun_confirmation_code"),
    stripeSessionId: varchar("stripe_session_id"),
    stripePaymentIntentId: varchar("stripe_payment_intent_id"),
    refundId: varchar("refund_id"),
    notes: varchar("notes"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("bookings_booking_reference_idx").on(columns.bookingReference),
    index("bookings_tour_idx").on(columns.tour),
    index("bookings_bokun_confirmation_code_idx").on(
      columns.bokunConfirmationCode,
    ),
    index("bookings_stripe_session_id_idx").on(columns.stripeSessionId),
    index("bookings_updated_at_idx").on(columns.updatedAt),
    index("bookings_created_at_idx").on(columns.createdAt),
  ],
);

export const blog_posts = pgTable(
  "blog_posts",
  {
    id: serial("id").primaryKey(),
    title: varchar("title"),
    slug: varchar("slug"),
    status: enum_blog_posts_status("status").default("draft"),
    publishedAt: timestamp("published_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    excerpt: varchar("excerpt"),
    coverImage: integer("cover_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    content: jsonb("content"),
    author: integer("author_id").references(() => users.id, {
      onDelete: "set null",
    }),
    seo_metaTitle: varchar("seo_meta_title"),
    seo_metaDescription: varchar("seo_meta_description"),
    seo_ogImage: integer("seo_og_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    _status: enum_blog_posts_status("_status").default("draft"),
  },
  (columns) => [
    uniqueIndex("blog_posts_slug_idx").on(columns.slug),
    index("blog_posts_cover_image_idx").on(columns.coverImage),
    index("blog_posts_author_idx").on(columns.author),
    index("blog_posts_seo_seo_og_image_idx").on(columns.seo_ogImage),
    index("blog_posts_updated_at_idx").on(columns.updatedAt),
    index("blog_posts_created_at_idx").on(columns.createdAt),
    index("blog_posts__status_idx").on(columns._status),
  ],
);

export const _blog_posts_v = pgTable(
  "_blog_posts_v",
  {
    id: serial("id").primaryKey(),
    parent: integer("parent_id").references(() => blog_posts.id, {
      onDelete: "set null",
    }),
    version_title: varchar("version_title"),
    version_slug: varchar("version_slug"),
    version_status:
      enum__blog_posts_v_version_status("version_status").default("draft"),
    version_publishedAt: timestamp("version_published_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_excerpt: varchar("version_excerpt"),
    version_coverImage: integer("version_cover_image_id").references(
      () => media.id,
      {
        onDelete: "set null",
      },
    ),
    version_content: jsonb("version_content"),
    version_author: integer("version_author_id").references(() => users.id, {
      onDelete: "set null",
    }),
    version_seo_metaTitle: varchar("version_seo_meta_title"),
    version_seo_metaDescription: varchar("version_seo_meta_description"),
    version_seo_ogImage: integer("version_seo_og_image_id").references(
      () => media.id,
      {
        onDelete: "set null",
      },
    ),
    version_updatedAt: timestamp("version_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp("version_created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version__status:
      enum__blog_posts_v_version_status("version__status").default("draft"),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    snapshot: boolean("snapshot"),
    publishedLocale: enum__blog_posts_v_published_locale("published_locale"),
    latest: boolean("latest"),
  },
  (columns) => [
    index("_blog_posts_v_parent_idx").on(columns.parent),
    index("_blog_posts_v_version_version_slug_idx").on(columns.version_slug),
    index("_blog_posts_v_version_version_cover_image_idx").on(
      columns.version_coverImage,
    ),
    index("_blog_posts_v_version_version_author_idx").on(
      columns.version_author,
    ),
    index("_blog_posts_v_version_seo_version_seo_og_image_idx").on(
      columns.version_seo_ogImage,
    ),
    index("_blog_posts_v_version_version_updated_at_idx").on(
      columns.version_updatedAt,
    ),
    index("_blog_posts_v_version_version_created_at_idx").on(
      columns.version_createdAt,
    ),
    index("_blog_posts_v_version_version__status_idx").on(
      columns.version__status,
    ),
    index("_blog_posts_v_created_at_idx").on(columns.createdAt),
    index("_blog_posts_v_updated_at_idx").on(columns.updatedAt),
    index("_blog_posts_v_snapshot_idx").on(columns.snapshot),
    index("_blog_posts_v_published_locale_idx").on(columns.publishedLocale),
    index("_blog_posts_v_latest_idx").on(columns.latest),
  ],
);

export const pages = pgTable(
  "pages",
  {
    id: serial("id").primaryKey(),
    title: varchar("title"),
    slug: varchar("slug"),
    content: jsonb("content"),
    seo_metaTitle: varchar("seo_meta_title"),
    seo_metaDescription: varchar("seo_meta_description"),
    seo_ogImage: integer("seo_og_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    _status: enum_pages_status("_status").default("draft"),
  },
  (columns) => [
    uniqueIndex("pages_slug_idx").on(columns.slug),
    index("pages_seo_seo_og_image_idx").on(columns.seo_ogImage),
    index("pages_updated_at_idx").on(columns.updatedAt),
    index("pages_created_at_idx").on(columns.createdAt),
    index("pages__status_idx").on(columns._status),
  ],
);

export const _pages_v = pgTable(
  "_pages_v",
  {
    id: serial("id").primaryKey(),
    parent: integer("parent_id").references(() => pages.id, {
      onDelete: "set null",
    }),
    version_title: varchar("version_title"),
    version_slug: varchar("version_slug"),
    version_content: jsonb("version_content"),
    version_seo_metaTitle: varchar("version_seo_meta_title"),
    version_seo_metaDescription: varchar("version_seo_meta_description"),
    version_seo_ogImage: integer("version_seo_og_image_id").references(
      () => media.id,
      {
        onDelete: "set null",
      },
    ),
    version_updatedAt: timestamp("version_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp("version_created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version__status:
      enum__pages_v_version_status("version__status").default("draft"),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    snapshot: boolean("snapshot"),
    publishedLocale: enum__pages_v_published_locale("published_locale"),
    latest: boolean("latest"),
  },
  (columns) => [
    index("_pages_v_parent_idx").on(columns.parent),
    index("_pages_v_version_version_slug_idx").on(columns.version_slug),
    index("_pages_v_version_seo_version_seo_og_image_idx").on(
      columns.version_seo_ogImage,
    ),
    index("_pages_v_version_version_updated_at_idx").on(
      columns.version_updatedAt,
    ),
    index("_pages_v_version_version_created_at_idx").on(
      columns.version_createdAt,
    ),
    index("_pages_v_version_version__status_idx").on(columns.version__status),
    index("_pages_v_created_at_idx").on(columns.createdAt),
    index("_pages_v_updated_at_idx").on(columns.updatedAt),
    index("_pages_v_snapshot_idx").on(columns.snapshot),
    index("_pages_v_published_locale_idx").on(columns.publishedLocale),
    index("_pages_v_latest_idx").on(columns.latest),
  ],
);

export const payload_kv = pgTable(
  "payload_kv",
  {
    id: serial("id").primaryKey(),
    key: varchar("key").notNull(),
    data: jsonb("data").notNull(),
  },
  (columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)],
);

export const payload_locked_documents = pgTable(
  "payload_locked_documents",
  {
    id: serial("id").primaryKey(),
    globalSlug: varchar("global_slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = pgTable(
  "payload_locked_documents_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
    mediaID: integer("media_id"),
    countriesID: integer("countries_id"),
    "tour-categoriesID": integer("tour_categories_id"),
    toursID: integer("tours_id"),
    bookingsID: integer("bookings_id"),
    "blog-postsID": integer("blog_posts_id"),
    pagesID: integer("pages_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_users_id_idx").on(columns.usersID),
    index("payload_locked_documents_rels_media_id_idx").on(columns.mediaID),
    index("payload_locked_documents_rels_countries_id_idx").on(
      columns.countriesID,
    ),
    index("payload_locked_documents_rels_tour_categories_id_idx").on(
      columns["tour-categoriesID"],
    ),
    index("payload_locked_documents_rels_tours_id_idx").on(columns.toursID),
    index("payload_locked_documents_rels_bookings_id_idx").on(
      columns.bookingsID,
    ),
    index("payload_locked_documents_rels_blog_posts_id_idx").on(
      columns["blog-postsID"],
    ),
    index("payload_locked_documents_rels_pages_id_idx").on(columns.pagesID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["countriesID"]],
      foreignColumns: [countries.id],
      name: "payload_locked_documents_rels_countries_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["tour-categoriesID"]],
      foreignColumns: [tour_categories.id],
      name: "payload_locked_documents_rels_tour_categories_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["toursID"]],
      foreignColumns: [tours.id],
      name: "payload_locked_documents_rels_tours_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["bookingsID"]],
      foreignColumns: [bookings.id],
      name: "payload_locked_documents_rels_bookings_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["blog-postsID"]],
      foreignColumns: [blog_posts.id],
      name: "payload_locked_documents_rels_blog_posts_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["pagesID"]],
      foreignColumns: [pages.id],
      name: "payload_locked_documents_rels_pages_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_preferences = pgTable(
  "payload_preferences",
  {
    id: serial("id").primaryKey(),
    key: varchar("key"),
    value: jsonb("value"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_preferences_rels = pgTable(
  "payload_preferences_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_users_id_idx").on(columns.usersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_migrations = pgTable(
  "payload_migrations",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    batch: numeric("batch", { mode: "number" }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ],
);

export const site_settings_testimonials = pgTable(
  "site_settings_testimonials",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    name: varchar("name").notNull(),
    location: varchar("location").notNull(),
    text: varchar("text").notNull(),
    rating: numeric("rating", { mode: "number" }).notNull(),
  },
  (columns) => [
    index("site_settings_testimonials_order_idx").on(columns._order),
    index("site_settings_testimonials_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [site_settings.id],
      name: "site_settings_testimonials_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const site_settings = pgTable(
  "site_settings",
  {
    id: serial("id").primaryKey(),
    heroImage: integer("hero_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    heroEyebrow: varchar("hero_eyebrow"),
    heroTitle: varchar("hero_title"),
    heroSubtitle: varchar("hero_subtitle"),
    ctaTitle: varchar("cta_title"),
    ctaSubtitle: varchar("cta_subtitle"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [index("site_settings_hero_image_idx").on(columns.heroImage)],
);

export const relations_users_sessions = relations(
  users_sessions,
  ({ one }) => ({
    _parentID: one(users, {
      fields: [users_sessions._parentID],
      references: [users.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: "sessions",
  }),
}));
export const relations_media = relations(media, () => ({}));
export const relations_countries = relations(countries, () => ({}));
export const relations_tour_categories = relations(tour_categories, () => ({}));
export const relations_tours_gallery = relations(tours_gallery, ({ one }) => ({
  _parentID: one(tours, {
    fields: [tours_gallery._parentID],
    references: [tours.id],
    relationName: "gallery",
  }),
  image: one(media, {
    fields: [tours_gallery.image],
    references: [media.id],
    relationName: "image",
  }),
}));
export const relations_tours_highlights = relations(
  tours_highlights,
  ({ one }) => ({
    _parentID: one(tours, {
      fields: [tours_highlights._parentID],
      references: [tours.id],
      relationName: "highlights",
    }),
  }),
);
export const relations_tours_included = relations(
  tours_included,
  ({ one }) => ({
    _parentID: one(tours, {
      fields: [tours_included._parentID],
      references: [tours.id],
      relationName: "included",
    }),
  }),
);
export const relations_tours_excluded = relations(
  tours_excluded,
  ({ one }) => ({
    _parentID: one(tours, {
      fields: [tours_excluded._parentID],
      references: [tours.id],
      relationName: "excluded",
    }),
  }),
);
export const relations_tours_itinerary = relations(
  tours_itinerary,
  ({ one }) => ({
    _parentID: one(tours, {
      fields: [tours_itinerary._parentID],
      references: [tours.id],
      relationName: "itinerary",
    }),
  }),
);
export const relations_tours_reviews = relations(tours_reviews, ({ one }) => ({
  _parentID: one(tours, {
    fields: [tours_reviews._parentID],
    references: [tours.id],
    relationName: "reviews",
  }),
}));
export const relations_tours_rels = relations(tours_rels, ({ one }) => ({
  parent: one(tours, {
    fields: [tours_rels.parent],
    references: [tours.id],
    relationName: "_rels",
  }),
  "tour-categoriesID": one(tour_categories, {
    fields: [tours_rels["tour-categoriesID"]],
    references: [tour_categories.id],
    relationName: "tour-categories",
  }),
}));
export const relations_tours = relations(tours, ({ one, many }) => ({
  gallery: many(tours_gallery, {
    relationName: "gallery",
  }),
  coverImage: one(media, {
    fields: [tours.coverImage],
    references: [media.id],
    relationName: "coverImage",
  }),
  country: one(countries, {
    fields: [tours.country],
    references: [countries.id],
    relationName: "country",
  }),
  highlights: many(tours_highlights, {
    relationName: "highlights",
  }),
  included: many(tours_included, {
    relationName: "included",
  }),
  excluded: many(tours_excluded, {
    relationName: "excluded",
  }),
  itinerary: many(tours_itinerary, {
    relationName: "itinerary",
  }),
  reviews: many(tours_reviews, {
    relationName: "reviews",
  }),
  seo_ogImage: one(media, {
    fields: [tours.seo_ogImage],
    references: [media.id],
    relationName: "seo_ogImage",
  }),
  _rels: many(tours_rels, {
    relationName: "_rels",
  }),
}));
export const relations__tours_v_version_gallery = relations(
  _tours_v_version_gallery,
  ({ one }) => ({
    _parentID: one(_tours_v, {
      fields: [_tours_v_version_gallery._parentID],
      references: [_tours_v.id],
      relationName: "version_gallery",
    }),
    image: one(media, {
      fields: [_tours_v_version_gallery.image],
      references: [media.id],
      relationName: "image",
    }),
  }),
);
export const relations__tours_v_version_highlights = relations(
  _tours_v_version_highlights,
  ({ one }) => ({
    _parentID: one(_tours_v, {
      fields: [_tours_v_version_highlights._parentID],
      references: [_tours_v.id],
      relationName: "version_highlights",
    }),
  }),
);
export const relations__tours_v_version_included = relations(
  _tours_v_version_included,
  ({ one }) => ({
    _parentID: one(_tours_v, {
      fields: [_tours_v_version_included._parentID],
      references: [_tours_v.id],
      relationName: "version_included",
    }),
  }),
);
export const relations__tours_v_version_excluded = relations(
  _tours_v_version_excluded,
  ({ one }) => ({
    _parentID: one(_tours_v, {
      fields: [_tours_v_version_excluded._parentID],
      references: [_tours_v.id],
      relationName: "version_excluded",
    }),
  }),
);
export const relations__tours_v_version_itinerary = relations(
  _tours_v_version_itinerary,
  ({ one }) => ({
    _parentID: one(_tours_v, {
      fields: [_tours_v_version_itinerary._parentID],
      references: [_tours_v.id],
      relationName: "version_itinerary",
    }),
  }),
);
export const relations__tours_v_version_reviews = relations(
  _tours_v_version_reviews,
  ({ one }) => ({
    _parentID: one(_tours_v, {
      fields: [_tours_v_version_reviews._parentID],
      references: [_tours_v.id],
      relationName: "version_reviews",
    }),
  }),
);
export const relations__tours_v_rels = relations(_tours_v_rels, ({ one }) => ({
  parent: one(_tours_v, {
    fields: [_tours_v_rels.parent],
    references: [_tours_v.id],
    relationName: "_rels",
  }),
  "tour-categoriesID": one(tour_categories, {
    fields: [_tours_v_rels["tour-categoriesID"]],
    references: [tour_categories.id],
    relationName: "tour-categories",
  }),
}));
export const relations__tours_v = relations(_tours_v, ({ one, many }) => ({
  parent: one(tours, {
    fields: [_tours_v.parent],
    references: [tours.id],
    relationName: "parent",
  }),
  version_gallery: many(_tours_v_version_gallery, {
    relationName: "version_gallery",
  }),
  version_coverImage: one(media, {
    fields: [_tours_v.version_coverImage],
    references: [media.id],
    relationName: "version_coverImage",
  }),
  version_country: one(countries, {
    fields: [_tours_v.version_country],
    references: [countries.id],
    relationName: "version_country",
  }),
  version_highlights: many(_tours_v_version_highlights, {
    relationName: "version_highlights",
  }),
  version_included: many(_tours_v_version_included, {
    relationName: "version_included",
  }),
  version_excluded: many(_tours_v_version_excluded, {
    relationName: "version_excluded",
  }),
  version_itinerary: many(_tours_v_version_itinerary, {
    relationName: "version_itinerary",
  }),
  version_reviews: many(_tours_v_version_reviews, {
    relationName: "version_reviews",
  }),
  version_seo_ogImage: one(media, {
    fields: [_tours_v.version_seo_ogImage],
    references: [media.id],
    relationName: "version_seo_ogImage",
  }),
  _rels: many(_tours_v_rels, {
    relationName: "_rels",
  }),
}));
export const relations_bookings = relations(bookings, ({ one }) => ({
  tour: one(tours, {
    fields: [bookings.tour],
    references: [tours.id],
    relationName: "tour",
  }),
}));
export const relations_blog_posts = relations(blog_posts, ({ one }) => ({
  coverImage: one(media, {
    fields: [blog_posts.coverImage],
    references: [media.id],
    relationName: "coverImage",
  }),
  author: one(users, {
    fields: [blog_posts.author],
    references: [users.id],
    relationName: "author",
  }),
  seo_ogImage: one(media, {
    fields: [blog_posts.seo_ogImage],
    references: [media.id],
    relationName: "seo_ogImage",
  }),
}));
export const relations__blog_posts_v = relations(_blog_posts_v, ({ one }) => ({
  parent: one(blog_posts, {
    fields: [_blog_posts_v.parent],
    references: [blog_posts.id],
    relationName: "parent",
  }),
  version_coverImage: one(media, {
    fields: [_blog_posts_v.version_coverImage],
    references: [media.id],
    relationName: "version_coverImage",
  }),
  version_author: one(users, {
    fields: [_blog_posts_v.version_author],
    references: [users.id],
    relationName: "version_author",
  }),
  version_seo_ogImage: one(media, {
    fields: [_blog_posts_v.version_seo_ogImage],
    references: [media.id],
    relationName: "version_seo_ogImage",
  }),
}));
export const relations_pages = relations(pages, ({ one }) => ({
  seo_ogImage: one(media, {
    fields: [pages.seo_ogImage],
    references: [media.id],
    relationName: "seo_ogImage",
  }),
}));
export const relations__pages_v = relations(_pages_v, ({ one }) => ({
  parent: one(pages, {
    fields: [_pages_v.parent],
    references: [pages.id],
    relationName: "parent",
  }),
  version_seo_ogImage: one(media, {
    fields: [_pages_v.version_seo_ogImage],
    references: [media.id],
    relationName: "version_seo_ogImage",
  }),
}));
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
    countriesID: one(countries, {
      fields: [payload_locked_documents_rels.countriesID],
      references: [countries.id],
      relationName: "countries",
    }),
    "tour-categoriesID": one(tour_categories, {
      fields: [payload_locked_documents_rels["tour-categoriesID"]],
      references: [tour_categories.id],
      relationName: "tour-categories",
    }),
    toursID: one(tours, {
      fields: [payload_locked_documents_rels.toursID],
      references: [tours.id],
      relationName: "tours",
    }),
    bookingsID: one(bookings, {
      fields: [payload_locked_documents_rels.bookingsID],
      references: [bookings.id],
      relationName: "bookings",
    }),
    "blog-postsID": one(blog_posts, {
      fields: [payload_locked_documents_rels["blog-postsID"]],
      references: [blog_posts.id],
      relationName: "blog-posts",
    }),
    pagesID: one(pages, {
      fields: [payload_locked_documents_rels.pagesID],
      references: [pages.id],
      relationName: "pages",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);
export const relations_site_settings_testimonials = relations(
  site_settings_testimonials,
  ({ one }) => ({
    _parentID: one(site_settings, {
      fields: [site_settings_testimonials._parentID],
      references: [site_settings.id],
      relationName: "testimonials",
    }),
  }),
);
export const relations_site_settings = relations(
  site_settings,
  ({ one, many }) => ({
    heroImage: one(media, {
      fields: [site_settings.heroImage],
      references: [media.id],
      relationName: "heroImage",
    }),
    testimonials: many(site_settings_testimonials, {
      relationName: "testimonials",
    }),
  }),
);

type DatabaseSchema = {
  enum__locales: typeof enum__locales;
  enum_users_role: typeof enum_users_role;
  enum_tours_status: typeof enum_tours_status;
  enum__tours_v_version_status: typeof enum__tours_v_version_status;
  enum__tours_v_published_locale: typeof enum__tours_v_published_locale;
  enum_bookings_status: typeof enum_bookings_status;
  enum_blog_posts_status: typeof enum_blog_posts_status;
  enum__blog_posts_v_version_status: typeof enum__blog_posts_v_version_status;
  enum__blog_posts_v_published_locale: typeof enum__blog_posts_v_published_locale;
  enum_pages_status: typeof enum_pages_status;
  enum__pages_v_version_status: typeof enum__pages_v_version_status;
  enum__pages_v_published_locale: typeof enum__pages_v_published_locale;
  users_sessions: typeof users_sessions;
  users: typeof users;
  media: typeof media;
  countries: typeof countries;
  tour_categories: typeof tour_categories;
  tours_gallery: typeof tours_gallery;
  tours_highlights: typeof tours_highlights;
  tours_included: typeof tours_included;
  tours_excluded: typeof tours_excluded;
  tours_itinerary: typeof tours_itinerary;
  tours_reviews: typeof tours_reviews;
  tours: typeof tours;
  tours_rels: typeof tours_rels;
  _tours_v_version_gallery: typeof _tours_v_version_gallery;
  _tours_v_version_highlights: typeof _tours_v_version_highlights;
  _tours_v_version_included: typeof _tours_v_version_included;
  _tours_v_version_excluded: typeof _tours_v_version_excluded;
  _tours_v_version_itinerary: typeof _tours_v_version_itinerary;
  _tours_v_version_reviews: typeof _tours_v_version_reviews;
  _tours_v: typeof _tours_v;
  _tours_v_rels: typeof _tours_v_rels;
  bookings: typeof bookings;
  blog_posts: typeof blog_posts;
  _blog_posts_v: typeof _blog_posts_v;
  pages: typeof pages;
  _pages_v: typeof _pages_v;
  payload_kv: typeof payload_kv;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  site_settings_testimonials: typeof site_settings_testimonials;
  site_settings: typeof site_settings;
  relations_users_sessions: typeof relations_users_sessions;
  relations_users: typeof relations_users;
  relations_media: typeof relations_media;
  relations_countries: typeof relations_countries;
  relations_tour_categories: typeof relations_tour_categories;
  relations_tours_gallery: typeof relations_tours_gallery;
  relations_tours_highlights: typeof relations_tours_highlights;
  relations_tours_included: typeof relations_tours_included;
  relations_tours_excluded: typeof relations_tours_excluded;
  relations_tours_itinerary: typeof relations_tours_itinerary;
  relations_tours_reviews: typeof relations_tours_reviews;
  relations_tours_rels: typeof relations_tours_rels;
  relations_tours: typeof relations_tours;
  relations__tours_v_version_gallery: typeof relations__tours_v_version_gallery;
  relations__tours_v_version_highlights: typeof relations__tours_v_version_highlights;
  relations__tours_v_version_included: typeof relations__tours_v_version_included;
  relations__tours_v_version_excluded: typeof relations__tours_v_version_excluded;
  relations__tours_v_version_itinerary: typeof relations__tours_v_version_itinerary;
  relations__tours_v_version_reviews: typeof relations__tours_v_version_reviews;
  relations__tours_v_rels: typeof relations__tours_v_rels;
  relations__tours_v: typeof relations__tours_v;
  relations_bookings: typeof relations_bookings;
  relations_blog_posts: typeof relations_blog_posts;
  relations__blog_posts_v: typeof relations__blog_posts_v;
  relations_pages: typeof relations_pages;
  relations__pages_v: typeof relations__pages_v;
  relations_payload_kv: typeof relations_payload_kv;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
  relations_site_settings_testimonials: typeof relations_site_settings_testimonials;
  relations_site_settings: typeof relations_site_settings;
};

declare module "@payloadcms/db-postgres" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
